# Form implementation generated from reading ui file 'Tasarım/about.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_about(object):
    def setupUi(self, MainWindow_about):
        MainWindow_about.setObjectName("MainWindow_about")
        MainWindow_about.resize(337, 525)
        MainWindow_about.setMinimumSize(QtCore.QSize(337, 525))
        MainWindow_about.setMaximumSize(QtCore.QSize(337, 525))
        MainWindow_about.setStyleSheet("QPushButton#linkedin, #instagram, #github, #bionluk,#twitch{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#linkedin:hover, #instagram:hover, #github:hover, #bionluk:hover,#twitch:hover{   color: rgba(131, 96, 53, 255);}\n"
"\n"
"QPushButton#linkedin:pressed, #instagram:pressed, #github:pressed, #bionluk:pressed,#twitch:pressed{\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   color:rgba(91, 88, 53, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_about)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background: #2d2d2d;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/lock_beyaz.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 75 24pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 15pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 13pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.linkedin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.linkedin.setMinimumSize(QtCore.QSize(50, 50))
        self.linkedin.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(30)
        self.linkedin.setFont(font)
        self.linkedin.setStyleSheet("QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{   color: rgba(131, 96, 53, 255);}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   color:rgba(91, 88, 53, 255);\n"
"}")
        self.linkedin.setIconSize(QtCore.QSize(50, 50))
        self.linkedin.setObjectName("linkedin")
        self.horizontalLayout_6.addWidget(self.linkedin)
        self.bionluk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bionluk.setMinimumSize(QtCore.QSize(50, 50))
        self.bionluk.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(30)
        self.bionluk.setFont(font)
        self.bionluk.setIconSize(QtCore.QSize(50, 50))
        self.bionluk.setObjectName("bionluk")
        self.horizontalLayout_6.addWidget(self.bionluk)
        self.twitch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.twitch.setMinimumSize(QtCore.QSize(50, 50))
        self.twitch.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(30)
        self.twitch.setFont(font)
        self.twitch.setIconSize(QtCore.QSize(50, 50))
        self.twitch.setObjectName("twitch")
        self.horizontalLayout_6.addWidget(self.twitch)
        self.github = QtWidgets.QPushButton(parent=self.centralwidget)
        self.github.setMinimumSize(QtCore.QSize(50, 50))
        self.github.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(30)
        self.github.setFont(font)
        self.github.setIconSize(QtCore.QSize(50, 50))
        self.github.setObjectName("github")
        self.horizontalLayout_6.addWidget(self.github)
        self.instagram = QtWidgets.QPushButton(parent=self.centralwidget)
        self.instagram.setMinimumSize(QtCore.QSize(50, 50))
        self.instagram.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(30)
        self.instagram.setFont(font)
        self.instagram.setIconSize(QtCore.QSize(50, 50))
        self.instagram.setObjectName("instagram")
        self.horizontalLayout_6.addWidget(self.instagram)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow_about.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_about)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_about.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_about)
        self.statusbar.setObjectName("statusbar")
        MainWindow_about.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_about)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_about)

    def retranslateUi(self, MainWindow_about):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_about.setWindowTitle(_translate("MainWindow_about", "MainWindow"))
        self.label_2.setText(_translate("MainWindow_about", "Password Manager"))
        self.label_3.setText(_translate("MainWindow_about", "Producer Fikret Karşıla"))
        self.label_5.setText(_translate("MainWindow_about", "Version 1.0"))
        self.linkedin.setText(_translate("MainWindow_about", "C"))
        self.bionluk.setText(_translate("MainWindow_about", "N"))
        self.twitch.setText(_translate("MainWindow_about", "a"))
        self.github.setText(_translate("MainWindow_about", ")"))
        self.instagram.setText(_translate("MainWindow_about", "Q"))
        self.label_4.setText(_translate("MainWindow_about", "Copyright © 2023  All rights reserved."))
