# Form implementation generated from reading ui file 'Tasarım/login_panel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_login(object):
    def setupUi(self, MainWindow_login):
        MainWindow_login.setObjectName("MainWindow_login")
        MainWindow_login.resize(396, 500)
        MainWindow_login.setMinimumSize(QtCore.QSize(396, 500))
        MainWindow_login.setMaximumSize(QtCore.QSize(396, 500))
        MainWindow_login.setSizeIncrement(QtCore.QSize(801, 600))
        MainWindow_login.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_login)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"  background: #2d2d2d;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, -150, 641, 561))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/smoke_beyaz.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-310, 330, 391, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/bullet_beyazpng.png"))
        self.label_3.setObjectName("label_3")
        self.reset_password = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_password.setGeometry(QtCore.QRect(30, 380, 165, 41))
        self.reset_password.setMinimumSize(QtCore.QSize(165, 41))
        self.reset_password.setMaximumSize(QtCore.QSize(165, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reset_password.setFont(font)
        self.reset_password.setStyleSheet("QPushButton {\n"
"  \n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  color: #a9a9a9;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset_password.setIcon(icon)
        self.reset_password.setIconSize(QtCore.QSize(16, 16))
        self.reset_password.setCheckable(False)
        self.reset_password.setFlat(True)
        self.reset_password.setObjectName("reset_password")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(93, 305, 245, 43))
        self.password.setMinimumSize(QtCore.QSize(245, 43))
        self.password.setMaximumSize(QtCore.QSize(245, 43))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setStyleSheet("#password {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#password:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login.setGeometry(QtCore.QRect(237, 380, 101, 41))
        self.login.setMinimumSize(QtCore.QSize(101, 41))
        self.login.setMaximumSize(QtCore.QSize(101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.eye_password_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.eye_password_login.setGeometry(QtCore.QRect(297, 313, 30, 30))
        self.eye_password_login.setMinimumSize(QtCore.QSize(30, 30))
        self.eye_password_login.setMaximumSize(QtCore.QSize(30, 30))
        self.eye_password_login.setMouseTracking(True)
        self.eye_password_login.setStyleSheet("QPushButton:pressed { background-color: transparent; }\n"
"")
        self.eye_password_login.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/view.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.eye_password_login.setIcon(icon1)
        self.eye_password_login.setIconSize(QtCore.QSize(30, 30))
        self.eye_password_login.setShortcut("")
        self.eye_password_login.setFlat(True)
        self.eye_password_login.setObjectName("eye_password_login")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 188, 188))
        self.label.setMinimumSize(QtCore.QSize(188, 188))
        self.label.setMaximumSize(QtCore.QSize(188, 188))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/lock_beyaz.png"))
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username.setGeometry(QtCore.QRect(93, 230, 245, 43))
        self.username.setMinimumSize(QtCore.QSize(245, 43))
        self.username.setMaximumSize(QtCore.QSize(245, 43))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setStyleSheet("#username {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#username:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.username.setInputMask("")
        self.username.setObjectName("username")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 430, 391, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.create_account = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.create_account.setMinimumSize(QtCore.QSize(165, 41))
        self.create_account.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.create_account.setFont(font)
        self.create_account.setStyleSheet("QPushButton {\n"
"  \n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 17px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  color: #a9a9a9;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/user_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.create_account.setIcon(icon2)
        self.create_account.setIconSize(QtCore.QSize(16, 16))
        self.create_account.setFlat(True)
        self.create_account.setObjectName("create_account")
        self.horizontalLayout.addWidget(self.create_account)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        MainWindow_login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_login)
        self.statusbar.setObjectName("statusbar")
        MainWindow_login.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_login)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_login)
        MainWindow_login.setTabOrder(self.username, self.password)
        MainWindow_login.setTabOrder(self.password, self.login)
        MainWindow_login.setTabOrder(self.login, self.reset_password)
        MainWindow_login.setTabOrder(self.reset_password, self.eye_password_login)

    def retranslateUi(self, MainWindow_login):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_login.setWindowTitle(_translate("MainWindow_login", "MainWindow"))
        self.reset_password.setText(_translate("MainWindow_login", "Reset Password"))
        self.password.setPlaceholderText(_translate("MainWindow_login", "Password"))
        self.login.setText(_translate("MainWindow_login", "Login"))
        self.username.setPlaceholderText(_translate("MainWindow_login", "Username"))
        self.create_account.setText(_translate("MainWindow_login", "Don\'t have an account ?"))
