# Form implementation generated from reading ui file 'Tasarım/login_panel.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_login(object):
    def setupUi(self, MainWindow_login):
        MainWindow_login.setObjectName("MainWindow_login")
        MainWindow_login.resize(396, 500)
        MainWindow_login.setMinimumSize(QtCore.QSize(396, 500))
        MainWindow_login.setMaximumSize(QtCore.QSize(396, 500))
        MainWindow_login.setSizeIncrement(QtCore.QSize(801, 600))
        MainWindow_login.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_login)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"  background: #2d2d2d;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, -10, 370, 473))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(188, 188))
        self.label.setMaximumSize(QtCore.QSize(188, 188))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/lock_beyaz.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.username = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.username.setMinimumSize(QtCore.QSize(245, 43))
        self.username.setMaximumSize(QtCore.QSize(245, 43))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setStyleSheet("#username {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"#username:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.username.setInputMask("")
        self.username.setObjectName("username")
        self.horizontalLayout_3.addWidget(self.username)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.password = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.password.setMinimumSize(QtCore.QSize(245, 43))
        self.password.setMaximumSize(QtCore.QSize(245, 43))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setStyleSheet("#password {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"#password:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reset_password = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.reset_password.setMinimumSize(QtCore.QSize(165, 41))
        self.reset_password.setMaximumSize(QtCore.QSize(155, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.reset_password.setFont(font)
        self.reset_password.setStyleSheet("QPushButton {\n"
"  \n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font-size: 14px;\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  color: #a9a9a9;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset_password.setIcon(icon)
        self.reset_password.setFlat(True)
        self.reset_password.setObjectName("reset_password")
        self.horizontalLayout_2.addWidget(self.reset_password)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.login = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.login.setMinimumSize(QtCore.QSize(101, 41))
        self.login.setMaximumSize(QtCore.QSize(101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font-size: 14px;\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.horizontalLayout_2.addWidget(self.login)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, -150, 641, 561))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/smoke_beyaz.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-310, 330, 391, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/bullet_beyazpng.png"))
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.layoutWidget.raise_()
        self.label_3.raise_()
        MainWindow_login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_login)
        self.statusbar.setObjectName("statusbar")
        MainWindow_login.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_login)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_login)

    def retranslateUi(self, MainWindow_login):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_login.setWindowTitle(_translate("MainWindow_login", "MainWindow"))
        self.username.setPlaceholderText(_translate("MainWindow_login", "Username"))
        self.password.setPlaceholderText(_translate("MainWindow_login", "Password"))
        self.reset_password.setText(_translate("MainWindow_login", "Reset Password"))
        self.login.setText(_translate("MainWindow_login", "Login"))
