# Form implementation generated from reading ui file 'Tasarım/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_main(object):
    def setupUi(self, MainWindow_main):
        MainWindow_main.setObjectName("MainWindow_main")
        MainWindow_main.resize(1190, 800)
        MainWindow_main.setMinimumSize(QtCore.QSize(1190, 800))
        MainWindow_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow_main.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_main)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background: #2d2d2d;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(398, 725))
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"   color:#fff;\n"
"   font: 11pt;\n"
"   border-radius: 10px;\n"
"   border: 2px solid #fff;\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_11.setSpacing(7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_20.setSpacing(5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.database_control = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.database_control.setMinimumSize(QtCore.QSize(50, 50))
        self.database_control.setMaximumSize(QtCore.QSize(50, 50))
        self.database_control.setStyleSheet("#database_control  {\n"
"    border-radius: 25px;\n"
"    background-color: red;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"")
        self.database_control.setText("")
        self.database_control.setObjectName("database_control")
        self.horizontalLayout_20.addWidget(self.database_control)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.label_control = QtWidgets.QLabel(parent=self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_control.setFont(font)
        self.label_control.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_control.setObjectName("label_control")
        self.horizontalLayout_20.addWidget(self.label_control)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.all_show = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.all_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.all_show.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/select_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.all_show.setIcon(icon)
        self.all_show.setIconSize(QtCore.QSize(22, 22))
        self.all_show.setObjectName("all_show")
        self.verticalLayout_11.addWidget(self.all_show)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Tasarım\\../Resimler/padlock_beyaz.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_18.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 24pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_19.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.user_settings = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.user_settings.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/profile_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user_settings.setIcon(icon1)
        self.user_settings.setIconSize(QtCore.QSize(22, 22))
        self.user_settings.setObjectName("user_settings")
        self.verticalLayout_11.addWidget(self.user_settings)
        self.change_user = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.change_user.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.change_user.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/changes_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.change_user.setIcon(icon2)
        self.change_user.setIconSize(QtCore.QSize(22, 22))
        self.change_user.setObjectName("change_user")
        self.verticalLayout_11.addWidget(self.change_user)
        self.about = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.about.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/info-button_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about.setIcon(icon3)
        self.about.setIconSize(QtCore.QSize(22, 22))
        self.about.setObjectName("about")
        self.verticalLayout_11.addWidget(self.about)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_11.addWidget(self.groupBox_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_data = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_data.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_data.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_data.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_data.setStyleSheet("QGroupBox {\n"
"   color:#fff;\n"
"   font: 11pt;\n"
"   border-radius: 10px;\n"
"   border: 2px solid #fff;\n"
"   font: 11pt \"Times New Roman\";\n"
"}\n"
"")
        self.groupBox_data.setTitle("")
        self.groupBox_data.setObjectName("groupBox_data")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_data)
        self.horizontalLayout_25.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_25.setSpacing(10)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.import_data = QtWidgets.QPushButton(parent=self.groupBox_data)
        self.import_data.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.import_data.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/import_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.import_data.setIcon(icon4)
        self.import_data.setIconSize(QtCore.QSize(22, 22))
        self.import_data.setObjectName("import_data")
        self.horizontalLayout_21.addWidget(self.import_data)
        self.export_data = QtWidgets.QPushButton(parent=self.groupBox_data)
        self.export_data.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.export_data.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/export_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.export_data.setIcon(icon5)
        self.export_data.setIconSize(QtCore.QSize(22, 22))
        self.export_data.setObjectName("export_data")
        self.horizontalLayout_21.addWidget(self.export_data)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_21)
        self.verticalLayout.addWidget(self.groupBox_data)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"   color:#fff;\n"
"   font: 11pt;\n"
"   border-radius: 10px;\n"
"   border: 2px solid #fff;\n"
"   font: 11pt \"Times New Roman\";\n"
"}\n"
"")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_23.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_23.setSpacing(5)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(5, 10, 5, 0)
        self.horizontalLayout_24.setSpacing(5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.id_del = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.id_del.setMinimumSize(QtCore.QSize(230, 40))
        self.id_del.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.id_del.setFont(font)
        self.id_del.setStyleSheet("#id_del {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#id_del:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.id_del.setInputMask("")
        self.id_del.setObjectName("id_del")
        self.horizontalLayout_24.addWidget(self.id_del)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem9)
        self.data_delete = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.data_delete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_delete.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/trash_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.data_delete.setIcon(icon6)
        self.data_delete.setIconSize(QtCore.QSize(22, 22))
        self.data_delete.setObjectName("data_delete")
        self.horizontalLayout_24.addWidget(self.data_delete)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_16.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"   color:#fff;\n"
"   font: 11pt;\n"
"   border-radius: 10px;\n"
"   border: 2px solid #fff;\n"
"   font: 11pt \"Times New Roman\";\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_17.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(5, 5, 5, 0)
        self.horizontalLayout_35.setSpacing(5)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.username_search = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.username_search.setMinimumSize(QtCore.QSize(230, 40))
        self.username_search.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username_search.setFont(font)
        self.username_search.setStyleSheet("#username_search {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#username_search:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.username_search.setInputMask("")
        self.username_search.setObjectName("username_search")
        self.horizontalLayout_35.addWidget(self.username_search)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem10)
        self.search = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.search.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.search.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Tasarım\\../Resimler/magnifier_beyaz.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search.setIcon(icon7)
        self.search.setIconSize(QtCore.QSize(22, 22))
        self.search.setObjectName("search")
        self.horizontalLayout_35.addWidget(self.search)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_16.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.girdiler = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.girdiler.setMinimumSize(QtCore.QSize(650, 0))
        self.girdiler.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.girdiler.setStyleSheet("#girdiler{\n"
"  background-color: #858585;\n"
"  border: none;\n"
"  font-weight: normal;\n"
"  color: #fff;\n"
"  border-radius: 10px;\n"
"  border: 7px solid #fff;\n"
"  font: 16px \"Times New Roman\";\n"
"}\n"
"\n"
"#girdiler::item {\n"
"background-color: #858585;\n"
"  padding: 5px;\n"
"  border-bottom: 1px solid #eee;\n"
"}\n"
"\n"
"#girdiler::item:selected {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"}\n"
"\n"
"#girdiler::item:focus {\n"
"  background-color: #ddd;\n"
"  color: #333;\n"
"}\n"
" ")
        self.girdiler.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Turkish, QtCore.QLocale.Country.Turkey))
        self.girdiler.setObjectName("girdiler")
        self.girdiler.setColumnCount(4)
        self.girdiler.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.girdiler.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.girdiler)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"   color:#fff;\n"
"   font: 11pt;\n"
"   border-radius: 10px;\n"
"   border: 2px solid #fff;\n"
"   font: 11pt \"Times New Roman\";\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.website_new = QtWidgets.QLineEdit(parent=self.groupBox)
        self.website_new.setMinimumSize(QtCore.QSize(230, 40))
        self.website_new.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.website_new.setFont(font)
        self.website_new.setStyleSheet("#website_new {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#website_new:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.website_new.setInputMask("")
        self.website_new.setObjectName("website_new")
        self.horizontalLayout_6.addWidget(self.website_new)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.username_new = QtWidgets.QLineEdit(parent=self.groupBox)
        self.username_new.setMinimumSize(QtCore.QSize(230, 40))
        self.username_new.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username_new.setFont(font)
        self.username_new.setStyleSheet("#username_new {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#username_new:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.username_new.setInputMask("")
        self.username_new.setObjectName("username_new")
        self.horizontalLayout_7.addWidget(self.username_new)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.password_new = QtWidgets.QLineEdit(parent=self.groupBox)
        self.password_new.setMinimumSize(QtCore.QSize(230, 40))
        self.password_new.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_new.setFont(font)
        self.password_new.setStyleSheet("#password_new {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#password_new:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.password_new.setInputMask("")
        self.password_new.setObjectName("password_new")
        self.horizontalLayout_8.addWidget(self.password_new)
        self.generate_password_new = QtWidgets.QPushButton(parent=self.groupBox)
        self.generate_password_new.setMinimumSize(QtCore.QSize(107, 51))
        self.generate_password_new.setMaximumSize(QtCore.QSize(107, 51))
        self.generate_password_new.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        self.generate_password_new.setObjectName("generate_password_new")
        self.horizontalLayout_8.addWidget(self.generate_password_new)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.password_repeat_new = QtWidgets.QLineEdit(parent=self.groupBox)
        self.password_repeat_new.setMinimumSize(QtCore.QSize(230, 40))
        self.password_repeat_new.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_repeat_new.setFont(font)
        self.password_repeat_new.setStyleSheet("#password_repeat_new {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font:18px \"Times New Roman\";\n"
"}\n"
"\n"
"#password_repeat_new:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.password_repeat_new.setInputMask("")
        self.password_repeat_new.setObjectName("password_repeat_new")
        self.horizontalLayout_9.addWidget(self.password_repeat_new)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.save_new = QtWidgets.QPushButton(parent=self.groupBox)
        self.save_new.setMinimumSize(QtCore.QSize(0, 0))
        self.save_new.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.save_new.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font-size: 14px;\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        self.save_new.setObjectName("save_new")
        self.horizontalLayout_5.addWidget(self.save_new)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(360, 311))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"   color:#fff;\n"
"   font: 11pt;\n"
"   border-radius: 10px;\n"
"   border: 2px solid #fff;\n"
"   font: 11pt \"Times New Roman\";\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 20, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.id_edit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.id_edit.setMinimumSize(QtCore.QSize(230, 40))
        self.id_edit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.id_edit.setFont(font)
        self.id_edit.setStyleSheet("#id_edit {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#id_edit:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.id_edit.setInputMask("")
        self.id_edit.setObjectName("id_edit")
        self.horizontalLayout_3.addWidget(self.id_edit)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.website_edit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.website_edit.setMinimumSize(QtCore.QSize(230, 40))
        self.website_edit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.website_edit.setFont(font)
        self.website_edit.setStyleSheet("#website_edit {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#website_edit:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.website_edit.setInputMask("")
        self.website_edit.setObjectName("website_edit")
        self.horizontalLayout_4.addWidget(self.website_edit)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.username_edit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.username_edit.setMinimumSize(QtCore.QSize(230, 40))
        self.username_edit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username_edit.setFont(font)
        self.username_edit.setStyleSheet("#username_edit {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#username_edit:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.username_edit.setInputMask("")
        self.username_edit.setObjectName("username_edit")
        self.horizontalLayout_12.addWidget(self.username_edit)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.password_edit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.password_edit.setMinimumSize(QtCore.QSize(230, 40))
        self.password_edit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("#password_edit {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#password_edit:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.password_edit.setInputMask("")
        self.password_edit.setObjectName("password_edit")
        self.horizontalLayout_13.addWidget(self.password_edit)
        self.generate_password_edit = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.generate_password_edit.setMinimumSize(QtCore.QSize(107, 51))
        self.generate_password_edit.setMaximumSize(QtCore.QSize(107, 51))
        self.generate_password_edit.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 16px \"Times New Roman\";\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        self.generate_password_edit.setObjectName("generate_password_edit")
        self.horizontalLayout_13.addWidget(self.generate_password_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.password_repeat_edit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.password_repeat_edit.setMinimumSize(QtCore.QSize(230, 40))
        self.password_repeat_edit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_repeat_edit.setFont(font)
        self.password_repeat_edit.setStyleSheet("#password_repeat_edit {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font: 18px \"Times New Roman\";\n"
"}\n"
"\n"
"#password_repeat_edit:focus {\n"
"border: 2px solid #fff;\n"
"  outline: none;\n"
"}\n"
"\n"
"\n"
"")
        self.password_repeat_edit.setInputMask("")
        self.password_repeat_edit.setObjectName("password_repeat_edit")
        self.horizontalLayout_14.addWidget(self.password_repeat_edit)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem20)
        self.save_change = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.save_change.setMinimumSize(QtCore.QSize(0, 0))
        self.save_change.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.save_change.setFont(font)
        self.save_change.setStyleSheet("QPushButton {\n"
"  background-color: #4A4A4A;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"  font-size: 14px;\n"
"\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #333;\n"
"}\n"
"")
        self.save_change.setObjectName("save_change")
        self.horizontalLayout_15.addWidget(self.save_change)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        MainWindow_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1190, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_main.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_main)
        MainWindow_main.setTabOrder(self.all_show, self.user_settings)
        MainWindow_main.setTabOrder(self.user_settings, self.change_user)
        MainWindow_main.setTabOrder(self.change_user, self.about)
        MainWindow_main.setTabOrder(self.about, self.id_del)
        MainWindow_main.setTabOrder(self.id_del, self.data_delete)
        MainWindow_main.setTabOrder(self.data_delete, self.username_search)
        MainWindow_main.setTabOrder(self.username_search, self.search)
        MainWindow_main.setTabOrder(self.search, self.girdiler)
        MainWindow_main.setTabOrder(self.girdiler, self.website_new)
        MainWindow_main.setTabOrder(self.website_new, self.username_new)
        MainWindow_main.setTabOrder(self.username_new, self.password_new)
        MainWindow_main.setTabOrder(self.password_new, self.generate_password_new)
        MainWindow_main.setTabOrder(self.generate_password_new, self.password_repeat_new)
        MainWindow_main.setTabOrder(self.password_repeat_new, self.save_new)
        MainWindow_main.setTabOrder(self.save_new, self.id_edit)
        MainWindow_main.setTabOrder(self.id_edit, self.website_edit)
        MainWindow_main.setTabOrder(self.website_edit, self.username_edit)
        MainWindow_main.setTabOrder(self.username_edit, self.password_edit)
        MainWindow_main.setTabOrder(self.password_edit, self.password_repeat_edit)
        MainWindow_main.setTabOrder(self.password_repeat_edit, self.generate_password_edit)
        MainWindow_main.setTabOrder(self.generate_password_edit, self.save_change)
        MainWindow_main.setTabOrder(self.save_change, self.database_control)

    def retranslateUi(self, MainWindow_main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_main.setWindowTitle(_translate("MainWindow_main", "MainWindow"))
        self.label_control.setText(_translate("MainWindow_main", "Database Not Connected"))
        self.all_show.setText(_translate("MainWindow_main", "All Show"))
        self.label_5.setText(_translate("MainWindow_main", "Password Manager"))
        self.user_settings.setText(_translate("MainWindow_main", "User Settings"))
        self.change_user.setText(_translate("MainWindow_main", "Change User"))
        self.about.setText(_translate("MainWindow_main", "About"))
        self.import_data.setText(_translate("MainWindow_main", "Import Data"))
        self.export_data.setText(_translate("MainWindow_main", "Export Data"))
        self.groupBox_5.setTitle(_translate("MainWindow_main", "Deletion Location"))
        self.id_del.setPlaceholderText(_translate("MainWindow_main", "Enter ID"))
        self.data_delete.setText(_translate("MainWindow_main", "Delete"))
        self.groupBox_3.setTitle(_translate("MainWindow_main", "Search Location"))
        self.username_search.setPlaceholderText(_translate("MainWindow_main", "Enter Username"))
        self.search.setText(_translate("MainWindow_main", "Search"))
        item = self.girdiler.verticalHeaderItem(0)
        item.setText(_translate("MainWindow_main", "1"))
        item = self.girdiler.verticalHeaderItem(1)
        item.setText(_translate("MainWindow_main", "2"))
        item = self.girdiler.verticalHeaderItem(2)
        item.setText(_translate("MainWindow_main", "3"))
        item = self.girdiler.verticalHeaderItem(3)
        item.setText(_translate("MainWindow_main", "4"))
        item = self.girdiler.verticalHeaderItem(4)
        item.setText(_translate("MainWindow_main", "5"))
        item = self.girdiler.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_main", "ID"))
        item = self.girdiler.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_main", "Website"))
        item = self.girdiler.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_main", "Username"))
        item = self.girdiler.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_main", "Password"))
        self.groupBox.setTitle(_translate("MainWindow_main", "Add New"))
        self.website_new.setPlaceholderText(_translate("MainWindow_main", "Website"))
        self.username_new.setPlaceholderText(_translate("MainWindow_main", "Username"))
        self.password_new.setPlaceholderText(_translate("MainWindow_main", "Password"))
        self.generate_password_new.setText(_translate("MainWindow_main", "Generate\n"
"Password"))
        self.password_repeat_new.setPlaceholderText(_translate("MainWindow_main", "Password Repeat"))
        self.save_new.setText(_translate("MainWindow_main", "Save"))
        self.groupBox_2.setTitle(_translate("MainWindow_main", "Edit Information"))
        self.id_edit.setPlaceholderText(_translate("MainWindow_main", "ID"))
        self.website_edit.setPlaceholderText(_translate("MainWindow_main", "Website"))
        self.username_edit.setPlaceholderText(_translate("MainWindow_main", "Username"))
        self.password_edit.setPlaceholderText(_translate("MainWindow_main", "Password"))
        self.generate_password_edit.setText(_translate("MainWindow_main", "Generate\n"
"Password"))
        self.password_repeat_edit.setPlaceholderText(_translate("MainWindow_main", "Password Repeat"))
        self.save_change.setText(_translate("MainWindow_main", "Save Change"))
